variables:
  BUILD_IMAGE: "$CI_REGISTRY_IMAGE/compile:build-$CI_PIPELINE_IID"
  BUILD_IMAGE_MAIN: "$CI_REGISTRY_IMAGE/compile:latest"

.docker-build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  tags:
    - docker

.docker-latest:
  extends: .docker-build
  variables:
    GIT_STRATEGY: none

docker-build:
  extends: [ .docker-build ]
  script:
    - docker pull $BUILD_IMAGE_MAIN || true
    - >
      docker build
      --pull
      --cache-from $BUILD_IMAGE_MAIN
      --tag $BUILD_IMAGE
      -f compile.Dockerfile
      .
    - docker push $BUILD_IMAGE
  only:
    - merge_requests
    - master

docker-latest:
  extends: [ .docker-latest ]
  needs: [ docker-build ]
  script:
    - docker pull $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $BUILD_IMAGE_MAIN
    - docker push $BUILD_IMAGE_MAIN
  only:
    - master

build:
  needs: [ docker-build ]
  image: $BUILD_IMAGE
  script:
    - cargo build
  only:
    - merge_requests
    - master

test:
  needs: [ docker-build ]
  image: $BUILD_IMAGE
  script:
    - cargo test --workspace
  only:
    - merge_requests
    - master

lint:
  needs: [ docker-build ]
  image: $BUILD_IMAGE
  script:
    - cargo clippy
  only:
    - merge_requests
    - master

telegram:
  image: registry.gitlab.com/clovis-ai/dotfiles:latest
  needs: [ ]
  script:
    - git changelog --format telegram-html --incoming >>changelog
    - cat changelog
    - announce-telegram changelog "$CHAT_IDS"
  only:
    - master

documentation:
  needs: [ docker-build ]
  image: $BUILD_IMAGE
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc
  only:
    - merge_requests
    - master

pages:
  needs: [ documentation ]
  image: alpine
  script:
    - mkdir -p public
    - cp -r target/doc public/documentation
  artifacts:
    paths:
      - public
  only:
    - master
